language: java
install: source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"
script: matlab-runner -xi .git -xi doc -sd unit_test "addpath ..; RunAllTests"
