sudo: required
services: docker
language: java

install:
 # install help2doc converter
 - git clone https://github.com/petercorke/help2doc $HOME/bin
 - export PATH="$(dirname "$HOME/bin"):$PATH"
 # install MATLAB unit test runner
 - source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"

before_script:
## build the doco PDF and place it in the src folder so it gets shipped to MATLAB cloud
 # create the LaTeX code
 - help2doc -l --include *.m
 # create the release file
 - printf '\\def\\release{%s}\n' `cat ../../../RELEASE` > release.tex
 - printf '\\def\\reldate{%s}\n' "`date '+%B %Y'`" >> release.tex
 - mv all.tex release.tex doc/manual
 # Compile all the LaTex code
 - docker run --mount src=$TRAVIS_BUILD_DIR/doc/manual,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic spatialmath.tex"
 # copy to src folder
 - mv doc/manual/spatialmath.pdf .

script:
 # run the unit tests on MATLAB cloud
 - matlab-runner -xi .git -xi doc -sd unit_test "addpath ..; RunAllTests"

after_success:
 # send to codecov
 - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: $GITRELEASE
  file:
    - spatialmath.pdf
#    - "Spatial Math Toolbox for MATLAB.mltbx"
  skip_cleanup: true
  draft: true 