language: java
install: source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"
script: matlab-runner "cd unit_test; results = runtests('IncludeSubfolders',true); assert(all(~[results.Failed]))"
